language: node_js
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: KAFKA_VERSION=0.10.2.2
      node_js: 8
    - os: linux
      dist: trusty
      sudo: false
      env: KAFKA_VERSION=0.10.2.2
      node_js: 10
    - os: linux
      dist: trusty
      sudo: false
      env: KAFKA_VERSION=0.11.0.3
      node_js: 10
    - os: linux
      dist: trusty
      sudo: false
      env: KAFKA_VERSION=1.1.0
      node_js: 10
    - os: linux
      dist: trusty
      sudo: false
      env: KAFKA_VERSION=2.0.0
      node_js: 10
cache:
  directories:
    - "node_modules"
before_install:
  - wget "http://www.us.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.11-${KAFKA_VERSION}.tgz" -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - echo -e "\nauto.create.topics.enable=true" >> ./kafka/config/server.properties
  - echo -e "\nnum.partitions=3" >> ./kafka/config/server.properties
  - cat ./kafka/config/zookeeper.properties
  - cat ./kafka/config/server.properties
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties > /dev/null 2>&1 &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties > /dev/null 2>&1 &"
  - sleep 10
  - cat ./kafka/logs/server.log
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run lint
  - NODE_ENV=ci ava dist/tests -v -s
